language: python
cache:
- pip
- ccache
matrix:
  include:
  - dist: trusty
    python: '2.7'
    env:
    - CHAINER_TRAVIS_TEST="chainer"
    - SKIP_CHAINERX=1
  - dist: trusty
    python: '3.4'
    env:
    - CHAINER_TRAVIS_TEST="chainer"
    - SKIP_CHAINERX=1
  - dist: xenial
    python: '3.5'
    env:
    - CHAINER_TRAVIS_TEST="chainer"
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
  - os: osx
    language: generic
    env:
    - CHAINER_TRAVIS_TEST="chainer"
    - PYTHON_VERSION=2.7.10
    - PYENV_ROOT=~/.pyenv
    - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    - SKIP_CHAINERX=1
  - os: osx
    language: generic
    env:
    - CHAINER_TRAVIS_TEST="chainer"
    - PYTHON_VERSION=3.4.4
    - PYENV_ROOT=~/.pyenv
    - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    - SKIP_CHAINERX=1
  - os: osx
    language: generic
    env:
    - CHAINER_TRAVIS_TEST="chainer"
    - PYTHON_VERSION=3.5.1
    - PYENV_ROOT=~/.pyenv
    - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"
before_install:
- bash scripts/ci/travis/run-tests.sh before_install
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
install:
- travis_wait bash scripts/ci/travis/run-tests.sh install
sudo: false
addons:
  apt:
    packages:
    - gfortran
    - libhdf5-serial-dev
    - liblapack-dev
    - openmpi-bin
    - openmpi-common
    - libopenmpi-dev
before_script:
- bash test_mypy.sh
script:
- echo "SCRIPT SECTION"
