language: python
cache:
- pip
- ccache
matrix:
  include:
  - name: Python Static Check
    dist: xenial
    python: '3.5'
    env:
    - CHAINER_TRAVIS_TEST="python-static-check"
  - name: C++ Static Check
    language: python
    dist: xenial
    python: '3.5'
    env:
    - CHAINER_TRAVIS_TEST="c-static-check"
  - name: Ubuntu16.04 Py35 | chainer, chainermn, chainerx, docs
    dist: xenial
    python: '3.5'
    env:
    - CHAINER_TRAVIS_TEST="chainer"
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - GOROOT=$HOME/go
  - name: macOS Py35 | chainer, chainermn, chainerx, docs
    os: osx
    language: generic
    env:
    - CHAINER_TRAVIS_TEST="chainer"
    - PYTHON_VERSION=3.5.2
    - PYENV_ROOT=~/.pyenv
    - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    - GOROOT=/usr/local/opt/go/libexec
before_install:
- bash scripts/ci/travis/run-tests.sh before_install
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
install:
- travis_wait bash scripts/ci/travis/run-tests.sh install
addons:
  apt:
    update: true
    packages:
    - moreutils
  homebrew:
    update: true
    packages:
    - moreutils
before_script:
- bash test_mypy.sh
script:
- echo "SCRIPT SECTION"
