language: python
cache:
- pip
- ccache
matrix:
  include:
  - os: linux
    python: '2.7'
  - os: linux
    python: '3.4'
  - os: linux
    python: '3.5'
  - os: osx
    language: generic
    env:
    - PYTHON_VERSION=2.7.10
    - PYENV_ROOT=~/.pyenv
    - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
  - os: osx
    language: generic
    env:
    - PYTHON_VERSION=3.4.4
    - PYENV_ROOT=~/.pyenv
    - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
  - os: osx
    language: generic
    env:
    - PYTHON_VERSION=3.5.1
    - PYENV_ROOT=~/.pyenv
    - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
before_install:
- 'if [[ $TRAVIS_OS_NAME = "osx" ]]; then brew update >/dev/null; brew outdated pyenv
  || brew upgrade --quiet pyenv;

  PYTHON_CONFIGURE_OPTS="--enable-unicode=ucs2" pyenv install -ks $PYTHON_VERSION;
  pyenv global $PYTHON_VERSION; python --version;

  brew cask uninstall oclint; brew install hdf5; brew install open-mpi; fi'
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
install:
- pip install -U pip wheel
- pip install mpi4py
- python setup.py sdist
- pip install dist/*.tar.gz
- travis_wait pip install -U -e .[travis]
sudo: false
addons:
  apt:
    packages:
    - gfortran
    - libhdf5-serial-dev
    - liblapack-dev
    - openmpi-bin
    - openmpi-common
    - libopenmpi-dev
before_script:
- bash test_mypy.sh
script:
- echo "SCRIPT SECTION"
